<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class DailyreportRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'userName' => ['required' , 'string' , 'max:20'],
            'department' => ['required' , 'string', 'max:10'],
            'date' => ['required' , 'date'],
            'amWeather' => ['string', 'max:20'],
            'pmWeather' => ['string', 'max:20'],
            'constructionNumber' => ['required' , 'string' , 'max:10'],
            'constructionName' => ['required' , 'string' , 'max:50'],
            // WARING: 本来であればかけるべきなのだが、おそらくNullが入ってきているため、エラーになる
            // 'laborTraderName1' =>  ['string', 'max:30'],
            // 'laborPeopleNumber1' => ['string', 'max:2'],
            // 'laborWorkTime1' => ['string', 'max:2'],
            // 'laborWorkVolume1' => ['string', 'max:50'],
            // 'laborTraderName2' =>  ['string', 'max:30'],
            // 'laborPeopleNumber2' => ['string', 'max:2'],
            // 'laborWorkTime2' => ['string', 'max:2'],
            // 'laborWorkVolume2' => ['string', 'max:50'],
            // 'laborTraderName3' =>  ['string', 'max:30'],
            // 'laborPeopleNumber3' => ['string', 'max:2'],
            // 'laborWorkTime3' => ['string', 'max:2'],
            // 'laborWorkVolume3' => ['string', 'max:50'],
            // 'laborTraderName4' =>  ['string', 'max:30'],
            // 'laborPeopleNumber4' => ['string', 'max:2'],
            // 'laborWorkTime4' => ['string', 'max:2'],
            // 'laborWorkVolume4' => ['string', 'max:50'],
            // 'laborTraderName5' =>  ['string', 'max:30'],
            // 'laborPeopleNumber5' => ['string', 'max:2'],
            // 'laborWorkTime5' => ['string', 'max:2'],
            // 'laborWorkVolume5' => ['string', 'max:50'],
            // 'laborTraderName6' =>  ['string', 'max:30'],
            // 'laborPeopleNumber6' => ['string', 'max:2'],
            // 'laborWorkTime6' => ['string', 'max:2'],
            // 'laborWorkVolume6' => ['string', 'max:50'],
            // 'laborTraderName7' =>  ['string', 'max:30'],
            // 'laborPeopleNumber7' => ['string', 'max:2'],
            // 'laborWorkTime7' => ['string', 'max:2'],
            // 'laborWorkVolume7' => ['string', 'max:50'],
            // 'laborTraderName8' =>  ['string', 'max:30'],
            // 'laborPeopleNumber8' => ['string', 'max:2'],
            // 'laborWorkTime8' => ['string', 'max:2'],
            // 'laborWorkVolume8' => ['string', 'max:50'],
            // 'heavyMachineryTraderName1' => ['string', 'max:30'],
            // 'heavyMachineryModel1' => ['string', 'max:30'],
            // 'heavyMachineryTime1' => ['string', 'max:10'],
            // 'heavyMachineryRemarks1' => ['string', 'max:50'],
            // 'heavyMachineryTraderName2' => ['string', 'max:30'],
            // 'heavyMachineryModel2' => ['string', 'max:30'],
            // 'heavyMachineryTime2' => ['string', 'max:10'],
            // 'heavyMachineryRemarks2' => ['string', 'max:50'],
            // 'heavyMachineryTraderName3' => ['string', 'max:30'],
            // 'heavyMachineryModel3' => ['string', 'max:30'],
            // 'heavyMachineryTime3' => ['string', 'max:10'],
            // 'heavyMachineryRemarks3' => ['string', 'max:50'],
            // 'heavyMachineryTraderName4' => ['string', 'max:30'],
            // 'heavyMachineryModel4' => ['string', 'max:30'],
            // 'heavyMachineryTime4' => ['string', 'max:10'],
            // 'heavyMachineryRemarks4' => ['string', 'max:50'],
            // 'heavyMachineryTraderName5' => ['string', 'max:30'],
            // 'heavyMachineryModel5' => ['string', 'max:30'],
            // 'heavyMachineryTime5' => ['string', 'max:10'],
            // 'heavyMachineryRemarks5' => ['string', 'max:50'],
            // 'heavyMachineryTraderName6' => ['string', 'max:30'],
            // 'heavyMachineryModel6' => ['string', 'max:30'],
            // 'heavyMachineryTime6' => ['string', 'max:10'],
            // 'heavyMachineryRemarks6' => ['string', 'max:50'],
            // 'materialTraderName1' => ['string', 'max:30'],
            // 'materialName1' => ['string', 'max:50'],
            // 'materialShapeDimensions1' => ['string', 'max:50'],
            // 'materialQuantity1' => ['string', 'max:10'],
            // 'materialUnit1' => ['string', 'max:10'],
            // 'materialResult1' => ['string', 'max:10'],
            // 'materialInspectionMethods1' => ['string', 'max:50'],
            // 'materialInspector1' => ['string', 'max:20'],
            // 'materialTraderName2' => ['string', 'max:30'],
            // 'materialName2' => ['string', 'max:50'],
            // 'materialShapeDimensions2' => ['string', 'max:50'],
            // 'materialQuantity2' => ['string', 'max:10'],
            // 'materialUnit2' => ['string', 'max:10'],
            // 'materialResult2' => ['string', 'max:10'],
            // 'materialInspectionMethods2' => ['string', 'max:50'],
            // 'materialInspector2' => ['string', 'max:20'],
            // 'materialTraderName3' => ['string', 'max:30'],
            // 'materialName3' => ['string', 'max:50'],
            // 'materialShapeDimensions3' => ['string', 'max:50'],
            // 'materialQuantity3' => ['string', 'max:10'],
            // 'materialUnit3' => ['string', 'max:10'],
            // 'materialResult3' => ['string', 'max:10'],
            // 'materialInspectionMethods3' => ['string', 'max:50'],
            // 'materialInspector3' => ['string', 'max:20'],
            // 'materialTraderName4' => ['string', 'max:30'],
            // 'materialName4' => ['string', 'max:50'],
            // 'materialShapeDimensions4' => ['string', 'max:50'],
            // 'materialQuantity4' => ['string', 'max:10'],
            // 'materialUnit4' => ['string', 'max:10'],
            // 'materialResult4' => ['string', 'max:10'],
            // 'materialInspectionMethods4' => ['string', 'max:50'],
            // 'materialInspector4' => ['string', 'max:20'],
            // 'materialTraderName5' => ['string', 'max:30'],
            // 'materialName5' => ['string', 'max:50'],
            // 'materialShapeDimensions5' => ['string', 'max:50'],
            // 'materialQuantity5' => ['string', 'max:10'],
            // 'materialUnit5' => ['string', 'max:10'],
            // 'materialResult5' => ['string', 'max:10'],
            // 'materialInspectionMethods5' => ['string', 'max:50'],
            // 'materialInspector5' => ['string', 'max:20'],
            // 'processName1' => ['string', 'max:50'],
            // 'processLocation1' => ['string', 'max:50'],
            // 'processMethods1' => ['string', 'max:50'],
            // 'processDocument1' => ['string', 'max:50'],
            // 'processResult1' => ['string', 'max:10'],
            // 'processInspector1' => ['string', 'max:20'],
            // 'processName2' => ['string', 'max:50'],
            // 'processLocation2' => ['string', 'max:50'],
            // 'processMethods2' => ['string', 'max:50'],
            // 'processDocument2' => ['string', 'max:50'],
            // 'processResult2' => ['string', 'max:10'],
            // 'processInspector2' => ['string', 'max:20'],
            // 'processName3' => ['string', 'max:50'],
            // 'processLocation3' => ['string', 'max:50'],
            // 'processMethods3' => ['string', 'max:50'],
            // 'processDocument3' => ['string', 'max:50'],
            // 'processResult3' => ['string', 'max:10'],
            // 'processInspector3' => ['string', 'max:20'],
            // 'processName4' => ['string', 'max:50'],
            // 'processLocation4' => ['string', 'max:50'],
            // 'processMethods4' => ['string', 'max:50'],
            // 'processDocument4' => ['string', 'max:50'],
            // 'processResult4' => ['string', 'max:10'],
            // 'processInspector4' => ['string', 'max:20'],
            // 'measuringEquipmentName1' => ['string', 'max:50'],
            // 'measuringEquipmentNumber1' => ['string', 'max:20'],
            // 'measuringEquipmentResult1' => ['string', 'max:10'],
            // 'measuringEquipmentRemarks1' => ['string', 'max:50'],
            // 'measuringEquipmentName2' => ['string', 'max:50'],
            // 'measuringEquipmentNumber2' => ['string', 'max:20'],
            // 'measuringEquipmentResult2' => ['string', 'max:10'],
            // 'measuringEquipmentRemarks2' => ['string', 'max:50'],
            'patrolResult' => ['string', 'max:10'],
            // 'patrolFindings' => ['string', 'max:500'],
        ];
    }

    public function dailyreportAttributes()
    {
        return $this->only([
            'id',
            'userName',
            'department',
            'date',
            'amWeather',
            'pmWeather',
            'constructionNumber',
            'constructionName',
            'laborTraderName1',
            'laborPeopleNumber1',
            'laborWorkTime1',
            'laborWorkVolume1',
            'laborTraderName2',
            'laborPeopleNumber2',
            'laborWorkTime2',
            'laborWorkVolume2',
            'laborTraderName3',
            'laborPeopleNumber3',
            'laborWorkTime3',
            'laborWorkVolume3',
            'laborTraderName4',
            'laborPeopleNumber4',
            'laborWorkTime4',
            'laborWorkVolume4',
            'laborTraderName5',
            'laborPeopleNumber5',
            'laborWorkTime5',
            'laborWorkVolume5',
            'laborTraderName6',
            'laborPeopleNumber6',
            'laborWorkTime6',
            'laborWorkVolume6',
            'laborTraderName7',
            'laborPeopleNumber7',
            'laborWorkTime7',
            'laborWorkVolume7',
            'laborTraderName8',
            'laborPeopleNumber8',
            'laborWorkTime8',
            'laborWorkVolume8',
            'heavyMachineryTraderName1',
            'heavyMachineryModel1',
            'heavyMachineryTime1',
            'heavyMachineryRemarks1',
            'heavyMachineryTraderName2',
            'heavyMachineryModel2',
            'heavyMachineryTime2',
            'heavyMachineryRemarks2',
            'heavyMachineryTraderName3',
            'heavyMachineryModel3',
            'heavyMachineryTime3',
            'heavyMachineryRemarks3',
            'heavyMachineryTraderName4',
            'heavyMachineryModel4',
            'heavyMachineryTime4',
            'heavyMachineryRemarks4',
            'heavyMachineryTraderName5',
            'heavyMachineryModel5',
            'heavyMachineryTime5',
            'heavyMachineryRemarks5',
            'heavyMachineryTraderName6',
            'heavyMachineryModel6',
            'heavyMachineryTime6',
            'heavyMachineryRemarks6',
            'materialTraderName1',
            'materialName1',
            'materialShapeDimensions1',
            'materialQuantity1',
            'materialUnit1',
            'materialResult1',
            'materialInspectionMethods1',
            'materialInspector1',
            'materialTraderName2',
            'materialName2',
            'materialShapeDimensions2',
            'materialQuantity2',
            'materialUnit2',
            'materialResult2',
            'materialInspectionMethods2',
            'materialInspector2',
            'materialTraderName3',
            'materialName3',
            'materialShapeDimensions3',
            'materialQuantity3',
            'materialUnit3',
            'materialResult3',
            'materialInspectionMethods3',
            'materialInspector3',
            'materialTraderName4',
            'materialName4',
            'materialShapeDimensions4',
            'materialQuantity4',
            'materialUnit4',
            'materialResult4',
            'materialInspectionMethods4',
            'materialInspector4',
            'materialTraderName5',
            'materialName5',
            'materialShapeDimensions5',
            'materialQuantity5',
            'materialUnit5',
            'materialResult5',
            'materialInspectionMethods5',
            'materialInspector5',
            'processName1',
            'processLocation1',
            'processMethods1',
            'processDocument1',
            'processResult1',
            'processInspector1',
            'processName2',
            'processLocation2',
            'processMethods2',
            'processDocument2',
            'processResult2',
            'processInspector2',
            'processName3',
            'processLocation3',
            'processMethods3',
            'processDocument3',
            'processResult3',
            'processInspector3',
            'processName4',
            'processLocation4',
            'processMethods4',
            'processDocument4',
            'processResult4',
            'processInspector4',
            'measuringEquipmentName1',
            'measuringEquipmentNumber1',
            'measuringEquipmentResult1',
            'measuringEquipmentRemarks1',
            'measuringEquipmentName2',
            'measuringEquipmentNumber2',
            'measuringEquipmentResult2',
            'measuringEquipmentRemarks2',
            'patrolResult',
            'patrolFindings',
            'updated_at'
        ]);
    }
}
